resolver: lts-17.5
compiler: ghc-9.0.1

allow-newer: true
system-ghc: true

packages:
- '.'

extra-deps:
# linear-base
- git: https://github.com/tweag/linear-base.git
  commit: f964890ef4470d13fe87b2c273d785e180ad19c3
